# -*- coding: utf-8 -*-
"""Agent1_Hello World_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ilh2gDtZ9EiNUE4RvYaJ4wiG3KW5VOVy
"""

!pip install langgraph langchain langchain-core

!pip install langchain-openai

!pip install langgraph
!pip install langgraph langchain langchain-core langchain-openai

from typing import TypedDict
from langgraph.graph import StateGraph, END

class AgentState(TypedDict):
  message : str

def gretting_node(state:AgentState) -> AgentState:
  """Simple node that adds a greeting message to the state """
  state['message'] = "Hey" + state["message"] + ", how is your day?"
  return state

graph=StateGraph(AgentState)
graph.add_node("greeter",gretting_node)
graph.set_entry_point("greeter")
graph.set_finish_point("greeter")
app=graph.compile()

result = app.invoke({'message' : "Bob"})
result["message"]